/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controller.DataBases;
import com.model.Dosen;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bayu Purnama Aji
 */
public final class cruddosen extends javax.swing.JFrame {
    private static final DataBases db = new DataBases();

    /**
     * Creates new form cruddosen
     */
    public cruddosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pempro = new javax.swing.JTextField();
        nip_dsn = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        nip = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        lihatabel = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pempro.setBorder(null);
        getContentPane().add(pempro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 370, 20));

        nip_dsn.setBorder(null);
        nip_dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nip_dsnActionPerformed(evt);
            }
        });
        getContentPane().add(nip_dsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 370, 20));

        email.setBorder(null);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 370, 20));

        nohp.setBorder(null);
        getContentPane().add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 370, 20));

        alamat.setBorder(null);
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 370, 20));

        nama.setBorder(null);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 370, 20));

        nip.setBorder(null);
        getContentPane().add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 370, 20));

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 147, 120, 40));

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 120, 40));

        lihatabel.setText("LIHAT TABEL");
        lihatabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatabelActionPerformed(evt);
            }
        });
        getContentPane().add(lihatabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 120, 40));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 297, 120, 40));

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 347, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/dosen.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nip_dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nip_dsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nip_dsnActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        try {
            new ubahdosen().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(cruddosen.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_ubahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
            String nipDosen = nip.getText();
            String namaDosen = nama.getText();
            String alamatDosen = alamat.getText();
            String nohpDosen = nohp.getText();
            String emailDosen = email.getText();
            String prodiDosen = pempro.getText();
            String nipDosenLain = nip_dsn.getText();
            
            int maxNIPLength = 18;
            int maxNamaLength = 35;
            int maxAlamatLength = 35;
            int maxNoHpLength = 15;
            int maxEmailLength = 30;
            int maxProdiLength = 5;
            int maxNipDosenLainLength = 18;
            
            if (nipDosen.isEmpty() || namaDosen.isEmpty() || alamatDosen.isEmpty() || nohpDosen.isEmpty() || emailDosen.isEmpty() || prodiDosen.isEmpty() || nipDosenLain.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap isi semua Data sebelum menyimpan data.");
            } else {
                try {
                    if (nipDosen.length() > maxNIPLength) {
                        JOptionPane.showMessageDialog(null, "Panjang NIP terlalu besar, maksimal " + maxNIPLength + " karakter.");
                        nip.setText(""); 
                    }

                    if (namaDosen.length() > maxNamaLength) {
                        JOptionPane.showMessageDialog(null, "Panjang Nama terlalu besar, maksimal " + maxNamaLength + " karakter.");
                        nama.setText(""); 
                    }

                    if (alamatDosen.length() > maxAlamatLength) {
                        JOptionPane.showMessageDialog(null, "Panjang Alamat terlalu besar, maksimal " + maxAlamatLength + " karakter.");
                        alamat.setText(""); 
                    }

                    if (nohpDosen.length() > maxNoHpLength) {
                        JOptionPane.showMessageDialog(null, "Panjang Nomor HP terlalu besar, maksimal " + maxNoHpLength + " karakter.");
                        nohp.setText(""); 
                    }

                    if (emailDosen.length() > maxEmailLength) {
                        JOptionPane.showMessageDialog(null, "Panjang Email terlalu besar, maksimal " + maxEmailLength + " karakter.");
                        email.setText(""); 
                    }

                    if (prodiDosen.length() > maxProdiLength) {
                        JOptionPane.showMessageDialog(null, "Panjang Prodi terlalu besar, maksimal " + maxProdiLength + " karakter.");
                        pempro.setText(""); 
                    }

                    if (nipDosenLain.length() > maxNipDosenLainLength) {
                        JOptionPane.showMessageDialog(null, "Panjang NIP Dosen Lain terlalu besar, maksimal " + maxNipDosenLainLength + " karakter.");
                        nip_dsn.setText(""); 
                    }
                    if (!nipDosen.matches("[0-9]+")) {
                        JOptionPane.showMessageDialog(null, "NIP harus berupa angka.");
                        nip.setText(""); 
                    }

                    if (namaDosen.matches(".*\\d.*")) {
                        JOptionPane.showMessageDialog(null, "Nama tidak boleh mengandung angka.");
                        nama.setText(""); 
                    }

                    if (!nohpDosen.matches("[0-9]+")) {
                        JOptionPane.showMessageDialog(null, "Nomor HP harus berupa angka.");
                        nohp.setText(""); 
                    }

                    if (!nipDosenLain.equals(nipDosen)) {
                        JOptionPane.showMessageDialog(null, "NIP Dosen Lain harus sama dengan NIP Dosen.");
                        nip_dsn.setText(""); 
                    }

                    if (!prodiDosen.matches("[0-9]+")) {
                        JOptionPane.showMessageDialog(null, "Prodi harus berupa angka.");
                        pempro.setText("");            
                    }

                    Dosen.createDosen(nipDosen, namaDosen, alamatDosen, nohpDosen, emailDosen, prodiDosen, nipDosenLain);
                    JOptionPane.showMessageDialog(null, "Data dosen telah berhasil disimpan.");
                } catch (SQLException ex) {
                    Logger.getLogger(cruddosen.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Gagal menyimpan data dosen."+ ex.getMessage());
                }
            }
    }//GEN-LAST:event_simpanActionPerformed

    private void lihatabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatabelActionPerformed
        try {
            new lihatdosen().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(cruddosen.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_lihatabelActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new menu_admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
            new hapusdosen().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(cruddosen.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.setVisible(false);
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cruddosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cruddosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cruddosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cruddosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cruddosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField email;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kembali;
    private javax.swing.JButton lihatabel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nip;
    private javax.swing.JTextField nip_dsn;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField pempro;
    private javax.swing.JButton simpan;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
