/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.model.Mata_Kuliah;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bayu Purnama Aji
 */
public final class crudmatakuliah extends javax.swing.JFrame {

    /**
     * Creates new form admin4
     */
    public crudmatakuliah() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        kd = new javax.swing.JTextField();
        nmk = new javax.swing.JTextField();
        sks = new javax.swing.JTextField();
        semester = new javax.swing.JTextField();
        praktikum = new javax.swing.JTextField();
        dpn = new javax.swing.JTextField();
        checkpeminatan = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 140, 120, 50));

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 190, 120, 50));

        lihat.setText("LIHAT TABEL");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        getContentPane().add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 120, 50));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 290, 120, 50));

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 340, 120, 50));

        kd.setBorder(null);
        getContentPane().add(kd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 116, 380, 30));

        nmk.setBorder(null);
        getContentPane().add(nmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 166, 380, 30));

        sks.setBorder(null);
        getContentPane().add(sks, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 216, 380, 30));

        semester.setBorder(null);
        getContentPane().add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 266, 380, 30));

        praktikum.setBorder(null);
        getContentPane().add(praktikum, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 316, 380, 30));

        dpn.setBorder(null);
        dpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpnActionPerformed(evt);
            }
        });
        getContentPane().add(dpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 380, 30));

        checkpeminatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkpeminatanActionPerformed(evt);
            }
        });
        getContentPane().add(checkpeminatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("PEMINATAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/Login (7).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String kodeMK = kd.getText();
        String namaMK = nmk.getText();
        String sksMK = sks.getText();
        String semesterMK = semester.getText();
        String praktikumMK = praktikum.getText();
        String dosenNIP = dpn.getText();

        int maxKodeMKLength = 12;
        int maxNamaMKLength = 30;
        int maxPraktikumLength = 5;

        try {
            if (kodeMK.isEmpty() || namaMK.isEmpty() || sksMK.isEmpty() || semesterMK.isEmpty() || praktikumMK.isEmpty() || dosenNIP.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap isi semua kolom sebelum menyimpan data.");
            } else {
                if (namaMK.matches(".*\\d.*") || kodeMK.matches(".*[\\p{Punct}].*")) {
                    JOptionPane.showMessageDialog(null, "Nama Mata Kuliah dan Kode Mata Kuliah tidak boleh mengandung angka atau karakter khusus.");
                    nmk.setText("");
                    kd.setText("");
                }
                if (kodeMK.length() > maxKodeMKLength) {
                    JOptionPane.showMessageDialog(null, "Panjang Kode Mata Kuliah terlalu besar, maksimal " + maxKodeMKLength + " karakter.");
                    kd.setText("");
                }

                if (sksMK.length() != 1 || !sksMK.matches("[0-9]")) {
                    JOptionPane.showMessageDialog(null, "SKS harus berupa satu digit angka.");
                    sks.setText("");
                }

                if (semesterMK.length() != 1 || !semesterMK.matches("[0-9]")) {
                    JOptionPane.showMessageDialog(null, "Semester harus berupa satu digit angka.");
                    semester.setText("");
                }

                if (praktikumMK.length() > maxPraktikumLength) {
                    JOptionPane.showMessageDialog(null, "Panjang Praktikum terlalu besar, maksimal " + maxPraktikumLength + " karakter.");
                    praktikum.setText("");
                }

                if (!dosenNIP.matches("[0-9]+")) {
                    JOptionPane.showMessageDialog(null, "NIP Dosen harus berupa angka.");
                    dpn.setText("");
                }

                Mata_Kuliah.createMata_Kuliah(kodeMK, namaMK, sksMK, semesterMK, praktikumMK, dosenNIP);
                JOptionPane.showMessageDialog(null, "Data mata kuliah berhasil disimpan.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(crudmatakuliah.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data mata kuliah. Silakan cek kembali data Anda.");
        }

    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        try {
            new ubahmk().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(crudmatakuliah.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_ubahActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        try {
            new lihatmatakuliah().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(crudmatakuliah.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_lihatActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
            new hapusmatakuliah().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(crudmatakuliah.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_hapusActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new menu_admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void dpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpnActionPerformed

    private void checkpeminatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkpeminatanActionPerformed
        if (checkpeminatan.isSelected()) {
            // Pilihan "Mata kuliah peminatan" dicentang, tampilkan deskripsi.
            JOptionPane.showMessageDialog(this, "Anda menjadikan mata kuliah yang ditambahkan sebagau peminatan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Pilihan "Mata kuliah peminatan" tidak dicentang.
            // Anda dapat menambahkan tindakan tambahan jika diperlukan saat tidak dicentang.
        }
    }//GEN-LAST:event_checkpeminatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudmatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudmatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudmatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudmatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudmatakuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkpeminatan;
    private javax.swing.JTextField dpn;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField kd;
    private javax.swing.JButton kembali;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField nmk;
    private javax.swing.JTextField praktikum;
    private javax.swing.JTextField semester;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField sks;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
