/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;



import com.controller.DataBases;
import com.model.Mahasiswa;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Bayu Purnama Aji
 */
public final class crudMahasiswa extends javax.swing.JFrame {
    private static final DataBases db = new DataBases();

    /**
     * Creates new form admin2
     */
    public crudMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        nimmhs = new javax.swing.JTextField();
        namamhs = new javax.swing.JTextField();
        alamatmhs = new javax.swing.JTextField();
        nohpmhs = new javax.swing.JTextField();
        emailmhs = new javax.swing.JTextField();
        promhs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambah.setText("SIMPAN");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 120, 40));

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 190, 120, 50));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 120, 50));

        lihat.setText("LIHAT TABEL");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        getContentPane().add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 120, 50));

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 120, 50));

        nimmhs.setBorder(null);
        getContentPane().add(nimmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 126, 350, 20));

        namamhs.setBorder(null);
        getContentPane().add(namamhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 176, 350, 20));

        alamatmhs.setBorder(null);
        getContentPane().add(alamatmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 226, 350, 20));

        nohpmhs.setBorder(null);
        getContentPane().add(nohpmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 276, 350, 20));

        emailmhs.setBorder(null);
        getContentPane().add(emailmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 350, 20));

        promhs.setBorder(null);
        promhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promhsActionPerformed(evt);
            }
        });
        getContentPane().add(promhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 350, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/crud mahasiswa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        try {
            new lihatmahasiswa().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(crudMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lihatActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String nimmahasiswa = nimmhs.getText();
        String namamahasiswa = namamhs.getText();
        String alamatmahasiswa = alamatmhs.getText();
        String nohpmahasiswa = nohpmhs.getText();
        String emailmahasiswa = emailmhs.getText();
        String prodimahasiswa = promhs.getText();

        int maxNIMLength = 10;
        int maxNamaLength = 35;
        int maxAlamatLength = 50;
        int maxNoHpLength = 15;
        int maxEmailLength = 30;
        int maxProdiLength = 5;

        if (nimmahasiswa.isEmpty() || namamahasiswa.isEmpty() || alamatmahasiswa.isEmpty() || nohpmahasiswa.isEmpty() || emailmahasiswa.isEmpty() || prodimahasiswa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi semua Data sebelum menyimpan data.");
        } else {
            try {
                if (nimmahasiswa.length() > maxNIMLength) {
                    JOptionPane.showMessageDialog(null, "Panjang NIM terlalu besar, maksimal " + maxNIMLength + " karakter.");
                    nimmhs.setText(""); 
                }

                if (!nimmahasiswa.matches("\\d+")) {
                    JOptionPane.showMessageDialog(null, "NIM harus berisi angka saja.");
                    nimmhs.setText(""); 
                }

                if (namamahasiswa.length() > maxNamaLength) {
                    JOptionPane.showMessageDialog(null, "Panjang Nama terlalu besar, maksimal " + maxNamaLength + " karakter.");
                    namamhs.setText(""); 
                }

                if (!namamahasiswa.matches("^[a-zA-Z ]+$")) {
                    JOptionPane.showMessageDialog(null, "Nama harus berisi huruf saja.");
                    namamhs.setText(""); 
                }

                if (alamatmahasiswa.length() > maxAlamatLength) {
                    JOptionPane.showMessageDialog(null, "Panjang Alamat terlalu besar, maksimal " + maxAlamatLength + " karakter.");
                    alamatmhs.setText(""); 
                }

                if (nohpmahasiswa.length() > maxNoHpLength) {
                    JOptionPane.showMessageDialog(null, "Panjang Nomor HP terlalu besar, maksimal " + maxNoHpLength + " karakter.");
                    nohpmhs.setText(""); 
                }

                if (!nohpmahasiswa.matches("\\d+")) {
                    JOptionPane.showMessageDialog(null, "Nomor HP harus berisi angka saja.");
                    nohpmhs.setText(""); 
                }

                if (emailmahasiswa.length() > maxEmailLength) {
                    JOptionPane.showMessageDialog(null, "Panjang Email terlalu besar, maksimal " + maxEmailLength + " karakter.");
                    emailmhs.setText(""); 
                }

                if (prodimahasiswa.length() > maxProdiLength) {
                    JOptionPane.showMessageDialog(null, "Panjang Program Studi terlalu besar, maksimal " + maxProdiLength + " karakter.");
                    promhs.setText(""); 
                }

                if (!prodimahasiswa.matches("\\d+")) {
                    JOptionPane.showMessageDialog(null, "Program Studi tidak valid.");
                    promhs.setText(""); 
                } else {
                   
                    Mahasiswa.createMahasiswa(nimmahasiswa, namamahasiswa, alamatmahasiswa, nohpmahasiswa, emailmahasiswa, prodimahasiswa);
                    String createTableQuery = String.format("CREATE TABLE %s (Kode_MK VARCHAR(12) PRIMARY KEY, Nama_MK VARCHAR(30), SKS CHAR(1), Semester CHAR(1), Praktikum VARCHAR(5), Dosen_NIP CHAR(18), Status BOOLEAN DEFAULT 0)", "krs_" + nimmahasiswa);
                    db.executeUpdateQuery(createTableQuery);

                    JOptionPane.showMessageDialog(null, "Data mahasiswa telah berhasil disimpan.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(cruddosen.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Gagal menyimpan data mahasiswa.");
            }
        }
    }//GEN-LAST:event_tambahActionPerformed

    
    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        try {
            new ubahmahasiswa().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(crudMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
            new hapusmahasiswa().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(crudMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_hapusActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new menu_admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void promhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatmhs;
    private javax.swing.JTextField emailmhs;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField namamhs;
    private javax.swing.JTextField nimmhs;
    private javax.swing.JTextField nohpmhs;
    private javax.swing.JTextField promhs;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
