/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;



import javax.swing.JOptionPane;
import com.model.Mahasiswa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bayu Purnama Aji
 */
public final class hapusmahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form admin5
     * @throws java.sql.SQLException
     */
    public hapusmahasiswa() throws SQLException {
        initComponents();
        tampil();
    }
    private void tampil() throws SQLException{
         ArrayList<Mahasiswa> mhs =Mahasiswa.readmahasiswa();
         System.out.println(mhs);
         DefaultTableModel modelmhs = (DefaultTableModel) tabeltampil.getModel();
         for (Mahasiswa mh : mhs) {
          String NIM = mh.getNIM();
          String Nama = mh.getNama();
          String Alamat = mh.getAlamat();
          String No_Hp  = mh.getNo_Hp();
          String Email  = mh.getEmail();
          String Prodi_Kode_Prodi = mh.getProdi_Kode_Prodi();
          modelmhs.addRow(new Object[]{NIM, Nama, Alamat, No_Hp, Email, Prodi_Kode_Prodi});
          
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltampil = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        nimmhs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabeltampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Alamat", "No. HP", "Email", "Program Studi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabeltampil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 80, 670, 260));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 120, 50));

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 120, 50));

        nimmhs.setBorder(null);
        getContentPane().add(nimmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 370, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/Login (8).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new crudMahasiswa().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    String nimMahasiswa = nimmhs.getText();

try {
    // Periksa apakah input NIM kosong
    if (nimMahasiswa.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Harap masukkan NIM sebelum menghapus data.");
    } else if (!nimMahasiswa.matches("\\d+")) {
        // Validasi NIM harus berupa angka, tidak boleh mengandung karakter selain angka
        JOptionPane.showMessageDialog(null, "NIM harus berupa angka tanpa karakter khusus atau huruf.");
    } else {
        Mahasiswa.deleteMahasiswa(nimMahasiswa);
        JOptionPane.showMessageDialog(null, "Mahasiswa dengan NIM " + nimMahasiswa + " telah dihapus.");
    }
} catch (SQLException ex) {
    Logger.getLogger(hapusmahasiswa.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "Gagal menghapus mahasiswa dengan NIM " + nimMahasiswa);
}      
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hapusmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hapusmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hapusmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hapusmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new hapusmahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(hapusmahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nimmhs;
    private javax.swing.JTable tabeltampil;
    // End of variables declaration//GEN-END:variables
}
