/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.model.Mata_Kuliah;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bayu Purnama Aji
 */
public final class hapusmatakuliah extends javax.swing.JFrame {

    /**
     * Creates new form hapusmatakuliah
     * @throws java.sql.SQLException
     */
    public hapusmatakuliah() throws SQLException {
        initComponents();
        tampil();
    }
    
    private void tampil() throws SQLException{
         ArrayList<Mata_Kuliah> mk =Mata_Kuliah.readMata_Kuliah();
         DefaultTableModel modelmhs = (DefaultTableModel) tampil1.getModel();
         modelmhs.setRowCount(0);
         
         for (Mata_Kuliah mkk : mk) {
          String KD = mkk.getKode_MK();
          String NKa = mkk.getNama_MK();
          String SKS = mkk.getSKS();
          String SMS  = mkk.getSemester();
          String PRAK  = mkk.getPraktikum();
          String DP =mkk.getDosen_NIP();
          modelmhs.addRow(new Object[]{KD, NKa,SKS, SMS, PRAK,DP});
          
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tampil1 = new javax.swing.JTable();
        kodemk = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tampil1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode MK", "Nama MK", "SKS", "Praktikum", "Dosen Pengajar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tampil1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 80, 670, 260));

        kodemk.setBorder(null);
        getContentPane().add(kodemk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 380, 30));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 130, 50));

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/Login (13).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        String kodeMataKuliah = kodemk.getText();

        try {
            // Periksa apakah input Kode Mata Kuliah kosong
            if (kodeMataKuliah.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap masukkan Kode Mata Kuliah sebelum menghapus data.");
            } else if (!kodeMataKuliah.matches("^[a-zA-Z0-9]+$")) {
                // Validasi Kode Mata Kuliah hanya boleh terdiri dari huruf dan angka
                JOptionPane.showMessageDialog(null, "Kode Mata Kuliah hanya boleh terdiri dari huruf dan angka, tanpa tanda strip atau karakter khusus.");
            } else {
                Mata_Kuliah.deleteMata_Kuliah(kodeMataKuliah);
                JOptionPane.showMessageDialog(null, "Mata Kuliah dengan Kode Mata Kuliah " + kodeMataKuliah + " telah dihapus.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(hapusmatakuliah.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Gagal menghapus Mata Kuliah dengan Kode Mata Kuliah " + kodeMataKuliah);
        }

    }//GEN-LAST:event_hapusActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new crudmatakuliah().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hapusmatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hapusmatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hapusmatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hapusmatakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new hapusmatakuliah().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(hapusmatakuliah.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField kodemk;
    private javax.swing.JTable tampil1;
    // End of variables declaration//GEN-END:variables
}
