/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.model.Mahasiswa;
import com.model.Mata_Kuliah;
import java.sql.SQLException;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public final class homekrsmhs extends javax.swing.JFrame {
    
    public Mahasiswa mahasiswa;
    
   
    public homekrsmhs(Mahasiswa mahasiswa) throws SQLException {
        this.mahasiswa = mahasiswa;
        initComponents();
        tampil();
    }
    
    private void tampil() throws SQLException{
         ArrayList<Mata_Kuliah> mk =Mata_Kuliah.readMata_Kuliah();
         DefaultTableModel modelmhs = (DefaultTableModel) tampil1.getModel();
         modelmhs.setRowCount(0);
         
         for (Mata_Kuliah mkk : mk) {
          String KD = mkk.getKode_MK();
          String NKa = mkk.getNama_MK();
          String SKS = mkk.getSKS();
          String SMS  = mkk.getSemester();
          String PRAK  = mkk.getPraktikum();
          String DP =mkk.getDosen_NIP();
          modelmhs.addRow(new Object[]{KD, NKa,SKS, SMS, PRAK,DP});
          
        }
        
    }
    
    public void selectRow(){
        int i = tampil1.getSelectedRow();
        TableModel model = tampil1.getModel();
        km.setText(model.getValueAt(i, 0).toString());
        nk.setText(model.getValueAt(i, 1).toString());
        sks.setText(model.getValueAt(i, 2).toString());
        sms.setText(model.getValueAt(i, 3).toString());
        prak.setText(model.getValueAt(i, 4).toString());
        dp.setText(model.getValueAt( i, 5).toString());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        krs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        log = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampil1 = new javax.swing.JTable();
        km = new javax.swing.JTextField();
        nk = new javax.swing.JTextField();
        sks = new javax.swing.JTextField();
        sms = new javax.swing.JTextField();
        prak = new javax.swing.JTextField();
        dp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        tampil = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        krs.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        krs.setText("KARTU STUDI MAHASISWA");
        krs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("MENU");

        log.setText("Log Out");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(krs, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(krs, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 420));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("SELAMAT DATANG PENERUS BANGSA!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        tampil1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode MK", "Nama Mk", "SKS", "Semester", "Praktikum", "Dosen Pengajar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tampil1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 570, 220));
        getContentPane().add(km, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 230, -1));

        nk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nkActionPerformed(evt);
            }
        });
        getContentPane().add(nk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 230, -1));
        getContentPane().add(sks, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 230, -1));
        getContentPane().add(sms, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 210, -1));
        getContentPane().add(prak, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 210, -1));

        dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpActionPerformed(evt);
            }
        });
        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 210, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Kode MK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Nama MK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("SKS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Semester");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Praktikum");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 90, -1));

        lihat.setText("LIHAT");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        getContentPane().add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 90, -1));

        tampil.setText("PILIH");
        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });
        getContentPane().add(tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 90, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("Dosen Pengajar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void krsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krsActionPerformed
        try {
            new homekrsmhs(null).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(homekrsmhs.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_krsActionPerformed

    private void nkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nkActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new homemhs(this.mahasiswa).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            new tampilan_login().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_logActionPerformed

    private void dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpActionPerformed

    }//GEN-LAST:event_dpActionPerformed

    private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
        if (adaItemDipilih()) {
        selectRow();
    } else {
        JOptionPane.showMessageDialog(this, "Anda belum memilih item. Silakan pilih item terlebih dahulu.");
    }
    }//GEN-LAST:event_tampilActionPerformed

    
    private boolean adaItemDipilih() {
        int selectedRow = tampil1.getSelectedRow();

        
        return selectedRow != -1; 
    }

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String tableName = "krs_" + this.mahasiswa.NIM;

        try {
            try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/krs1", "root", "")) {
                int selectedRow = tampil1.getSelectedRow();

                if (selectedRow == -1) {
                    JOptionPane.showMessageDialog(this, "Pilih baris di tabel terlebih dahulu.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                } else {
                    String kodeMK = km.getText();
                    String checkExistingQuery = String.format("SELECT COUNT(*) FROM %s WHERE Kode_MK = ?", tableName);
                    PreparedStatement checkExistingStatement = connection.prepareStatement(checkExistingQuery);
                    checkExistingStatement.setString(1, kodeMK);
                    ResultSet resultSet = checkExistingStatement.executeQuery();
                    resultSet.next();
                    int count = resultSet.getInt(1);

                    if (count > 0) {
                        JOptionPane.showMessageDialog(this, "Mata kuliah dengan kode " + kodeMK + " sudah ada di database.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    } else {
                        String insertDataQuery = String.format("INSERT INTO %s (Kode_MK, Nama_MK, SKS, Semester, Praktikum, Dosen_NIP, Status) VALUES (?, ?, ?, ?, ?, ?, ?)", tableName);
                        PreparedStatement preparedStatement = connection.prepareStatement(insertDataQuery);
                        preparedStatement.setString(1, km.getText());
                        preparedStatement.setString(2, nk.getText());
                        preparedStatement.setString(3, sks.getText());
                        preparedStatement.setString(4, sms.getText());
                        preparedStatement.setString(5, prak.getText());
                        preparedStatement.setString(6, dp.getText());
                        preparedStatement.setString(7, "0");
                        int rowsInserted = preparedStatement.executeUpdate();
                        if (rowsInserted > 0) {
                            JOptionPane.showMessageDialog(null, "Data telah berhasil ditambahkan ke "+ " " + tableName);
                        }
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Gagal menyimpan data ke tabel " + tableName);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_tambahActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        try {
            new lihatmatakuliah1(this.mahasiswa).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(homekrsmhs.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_lihatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homekrsmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homekrsmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homekrsmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homekrsmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new homekrsmhs(null).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(homekrsmhs.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dp;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField km;
    private javax.swing.JButton krs;
    private javax.swing.JButton lihat;
    private javax.swing.JButton log;
    private javax.swing.JTextField nk;
    private javax.swing.JTextField prak;
    private javax.swing.JTextField sks;
    private javax.swing.JTextField sms;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tampil;
    private javax.swing.JTable tampil1;
    // End of variables declaration//GEN-END:variables

    private void tampil1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
