/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.model.Dosen;
import com.model.Mahasiswa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;


public final class homekrsdosen extends javax.swing.JFrame {

//    public Mahasiswa mahasiswa;
    public Dosen dosen;
    
    public homekrsdosen(Dosen dosen) throws SQLException {
        this.dosen =dosen;
//        this.mahasiswa =mahasiswa;
        
        initComponents();
        tampil();
    }
    
    private void tampil() throws SQLException {
        try {
            ArrayList<Mahasiswa> mhs = Mahasiswa.readmahasiswa();
            DefaultTableModel modelmhs = (DefaultTableModel) tampil1.getModel();
            for (Mahasiswa mh : mhs) {
                String NIM = mh.getNIM();
                String Nama = mh.getNama();
                String Alamat = mh.getAlamat();
                String No_Hp = mh.getNo_Hp();
                String Email = mh.getEmail();
                String Prodi_Kode_Prodi = mh.getProdi_Kode_Prodi();
                modelmhs.addRow(new Object[]{NIM, Nama, Alamat, No_Hp, Email, Prodi_Kode_Prodi});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil data mahasiswa.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void selectRow(){
        int i = tampil1.getSelectedRow();
        TableModel model = tampil1.getModel();
        nim.setText(model.getValueAt(i, 0).toString());
        nama.setText(model.getValueAt(i, 1).toString());
        alamat.setText(model.getValueAt(i, 2).toString());
        nohp.setText(model.getValueAt(i, 3).toString());
        email.setText(model.getValueAt(i, 4).toString());
        program.setText(model.getValueAt( i, 5).toString());   
    }
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        krs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        log = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampil1 = new javax.swing.JTable();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        program = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PILIH = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();
        Masuk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        krs.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        krs.setText("KARTU STUDI MAHASISWA");
        krs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("MENU");

        log.setText("Log Out");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(krs, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(krs, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 420));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("SELAMAT DATANG PENGAJAR HEBAT!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        tampil1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama ", "Alamat", "No HP", "Email", "Program Studi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tampil1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 570, 220));
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 230, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 230, -1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 230, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 210, -1));
        getContentPane().add(program, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 210, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("NIM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 40, 10));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Program Studi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        PILIH.setText("PILIH");
        PILIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILIHActionPerformed(evt);
            }
        });
        getContentPane().add(PILIH, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 80, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("No HP");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, 20));

        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });
        getContentPane().add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 210, -1));

        Masuk.setText("CEK KRS");
        Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukActionPerformed(evt);
            }
        });
        getContentPane().add(Masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 80, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("TABEL MAHASISWA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void krsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krsActionPerformed
        try {
            new homekrsdosen(this.dosen).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(homekrsdosen.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_krsActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new homedosen(this.dosen).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            new tampilan_login().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_logActionPerformed

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed

    }//GEN-LAST:event_nohpActionPerformed

    private void PILIHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PILIHActionPerformed
        if(adaItemDipilih()) {
            selectRow();
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih item. Silakan pilih item terlebih dahulu.");
            }
    }//GEN-LAST:event_PILIHActionPerformed

    private boolean adaItemDipilih() {
        
        int selectedRow = tampil1.getSelectedRow();

       
        return selectedRow != -1; 
    }
    private void MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukActionPerformed

    int selectedRow = tampil1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris di tabel terlebih dahulu.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    } else {
        String mahasiswaNIM = tampil1.getValueAt(selectedRow, 1).toString();
        String mahasiswaPassword = tampil1.getValueAt(selectedRow, 0).toString();
        boolean loginSuccess = loginMahasiswa(mahasiswaPassword, mahasiswaNIM);
        if (loginSuccess) {
            try {
                System.out.println("Sukses");
                dosenlihatmatakuliah11 dosenLihatMataKuliah11 = new dosenlihatmatakuliah11(mahasiswaPassword, mahasiswaNIM);
                dosenLihatMataKuliah11.setVisible(true);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(homekrsdosen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Login mahasiswa gagal. Periksa NIM dan kata sandi.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
}

    private boolean loginMahasiswa(String NIM, String password) {
        
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/krs1", "root", "")) {
            String tableName = "mahasiswa"; 
            String query = "SELECT NIM, Nama FROM " + tableName + " WHERE NIM =?";
            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, NIM);
                System.out.println("nim" + NIM + "pass" + password);
                ResultSet resultSet = statement.executeQuery();
                while (resultSet.next()) {                    
                    String nim = resultSet.getString("NIM");
                    String nama = resultSet.getString("Nama");
                    if (NIM.equals(nim) && password.equals(nama)) {
                        return true;
                    }
                }
//                int count = resultSet.getInt(1);
//                return count > 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(homekrsdosen.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        return false;
    }//GEN-LAST:event_MasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homekrsdosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homekrsdosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homekrsdosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homekrsdosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new homekrsdosen(null).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(homekrsdosen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Masuk;
    private javax.swing.JButton PILIH;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField email;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton krs;
    private javax.swing.JButton log;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField program;
    private javax.swing.JTable tampil1;
    // End of variables declaration//GEN-END:variables

    private boolean isValidNIM(String selectedNIM) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
