/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Bayu Purnama Aji
 */
public final class menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form admin1
     */
    public menu_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datamatakuliah = new javax.swing.JButton();
        datadosen = new javax.swing.JButton();
        datamahasiswa = new javax.swing.JButton();
        log = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datamatakuliah.setText("DATA MATA KULIAH");
        datamatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamatakuliahActionPerformed(evt);
            }
        });
        getContentPane().add(datamatakuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 160, 90));

        datadosen.setText("DATA DOSEN");
        datadosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datadosenActionPerformed(evt);
            }
        });
        getContentPane().add(datadosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 160, 90));

        datamahasiswa.setText("DATA MAHASISWA");
        datamahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamahasiswaActionPerformed(evt);
            }
        });
        getContentPane().add(datamahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 347, 170, 90));

        log.setText("Log Out");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/Login (4).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datamatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamatakuliahActionPerformed
        new crudmatakuliah().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_datamatakuliahActionPerformed

    private void datadosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datadosenActionPerformed
        new cruddosen().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_datadosenActionPerformed

    private void datamahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamahasiswaActionPerformed
        new crudMahasiswa().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_datamahasiswaActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            new tampilan_login().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_logActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datadosen;
    private javax.swing.JButton datamahasiswa;
    private javax.swing.JButton datamatakuliah;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton log;
    // End of variables declaration//GEN-END:variables
}
