/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controller.DataBases;
import com.controller.LoginControlDosen;
import com.controller.LoginControlmahasiswa;
import com.model.Dosen;
import com.model.Mahasiswa;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Bayu Purnama Aji
 */
public final class tampilan_login extends javax.swing.JFrame {
    DataBases db = new DataBases();
   
    public tampilan_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonlogin = new javax.swing.JButton();
        isi_username = new javax.swing.JTextField();
        isi_password = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonlogin.setBackground(new java.awt.Color(84, 164, 189));
        buttonlogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonlogin.setText("LOGIN");
        buttonlogin.setBorder(null);
        buttonlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonloginMouseClicked(evt);
            }
        });
        buttonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonloginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 270, 40));

        isi_username.setBackground(new java.awt.Color(237, 237, 237));
        isi_username.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        isi_username.setForeground(new java.awt.Color(3, 3, 3));
        isi_username.setBorder(null);
        isi_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(isi_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 370, 30));

        isi_password.setBackground(new java.awt.Color(237, 237, 237));
        isi_password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        isi_password.setBorder(null);
        getContentPane().add(isi_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 370, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Dosen", "Mahasiswa" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/tampilan log.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isi_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isi_usernameActionPerformed

    private void buttonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonloginActionPerformed
    LoginControlmahasiswa controler = new LoginControlmahasiswa();
    LoginControlDosen dsn = new LoginControlDosen();

    if (jComboBox1.getSelectedItem().equals("Mahasiswa")) {
        Mahasiswa mahasiswa = controler.login(isi_username.getText(), isi_password.getText());
        if (mahasiswa != null) {
            new homemhs(mahasiswa).setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Username dan Password Anda salah.");
        }
    } else if (jComboBox1.getSelectedItem().equals("Dosen")) {
         Dosen dosen = dsn.login(isi_username.getText(), isi_password.getText());
        if (dosen !=null) {
            new homedosen(dosen).setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Username dan Password Anda salah.");
        }
    } else if (jComboBox1.getSelectedItem().equals("Admin")) {
        String username = isi_username.getText();
        String password = isi_password.getText();

        if (username.equals("admin") && password.equals("1234")) {
            JOptionPane.showMessageDialog(null, "Login admin berhasil!");
            new menu_admin().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Login admin gagal. Periksa kembali username dan password.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih role yang valid.");
    }
 
    }//GEN-LAST:event_buttonloginActionPerformed

    private void buttonloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonloginMouseClicked
      
    }//GEN-LAST:event_buttonloginMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan_login().setVisible(true);
            }
        });
    }

    public JButton getButtonlogin() {
        return buttonlogin;
    }

    public void setButtonlogin(JButton buttonlogin) {
        this.buttonlogin = buttonlogin;
    }

    public JPasswordField getIsi_password() {
        return isi_password;
    }

    public void setIsi_password(JPasswordField isi_password) {
        this.isi_password = isi_password;
    }

    public JTextField getIsi_username() {
        return isi_username;
    }

    public void setIsi_username(JTextField isi_username) {
        this.isi_username = isi_username;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonlogin;
    private javax.swing.JPasswordField isi_password;
    private javax.swing.JTextField isi_username;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
