/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;
import com.model.Mahasiswa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bayu Purnama Aji
 */
public final class ubahmahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form ubahmahasiswa
     * @throws java.sql.SQLException
     */
    public ubahmahasiswa() throws SQLException {
        initComponents();
        tampil();
    }
    
 
    private void tampil() throws SQLException{
         ArrayList<Mahasiswa> mhs =Mahasiswa.readmahasiswa();
         System.out.println(mhs);
         DefaultTableModel modelmhs = (DefaultTableModel) tampil1.getModel();
         for (Mahasiswa mh : mhs) {
          String NIM = mh.getNIM();
          String Nama = mh.getNama();
          String Alamat = mh.getAlamat();
          String No_Hp  = mh.getNo_Hp();
          String Email  = mh.getEmail();
          String Prodi_Kode_Prodi =mh.getProdi_Kode_Prodi();
          modelmhs.addRow(new Object[]{NIM, Nama, Alamat, No_Hp, Email, Prodi_Kode_Prodi});
          
        }
        
    }
    
    public void selectRow(){
        int i = tampil1.getSelectedRow();
        TableModel model = tampil1.getModel();
        nimmhs.setText(model.getValueAt(i, 0).toString());
        programmhs.setText(model.getValueAt( i, 5).toString());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tampil1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nimmhs = new javax.swing.JTextField();
        namamhs = new javax.swing.JTextField();
        alamatmhs = new javax.swing.JTextField();
        nohpmhs = new javax.swing.JTextField();
        emailmhs = new javax.swing.JTextField();
        ubah = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        programmhs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tampil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tampil1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Alamat", "No. HP", "Email", "Program Studi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tampil1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 530, 260));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("DATA MAHASISWA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));
        getContentPane().add(nimmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 220, -1));
        getContentPane().add(namamhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 220, -1));
        getContentPane().add(alamatmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 220, -1));
        getContentPane().add(nohpmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 220, -1));
        getContentPane().add(emailmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 220, -1));

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 100, 30));

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 90, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("NIM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("No HP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, 20));

        programmhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programmhsActionPerformed(evt);
            }
        });
        getContentPane().add(programmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 220, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Program Studi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        tampil.setText("PILIH");
        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });
        getContentPane().add(tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 380, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/Login (16).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void programmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programmhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programmhsActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        int row = tampil1.getSelectedRow();
if (row >= 0) {
    DefaultTableModel model = (DefaultTableModel) tampil1.getModel();
    String nimmahasiswa = model.getValueAt(row, 0).toString();
    String namamahasiswa = namamhs.getText();
    String alamatmahasiswa = alamatmhs.getText();
    String nohpmahasiswa = nohpmhs.getText();
    String emailmahasiswa = emailmhs.getText();
    String prodi = model.getValueAt(row, 5).toString();
    
    if (nimmahasiswa.isEmpty() || namamahasiswa.isEmpty() || alamatmahasiswa.isEmpty() || nohpmahasiswa.isEmpty() || emailmahasiswa.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Harap isi semua data kecuali NIM dan Prodi sebelum mengubah data.");
    } else {
      
        if (namamahasiswa.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Nama Mahasiswa tidak boleh mengandung angka.");
        }
        
        if (nohpmahasiswa.matches(".*[a-zA-Z]+.*")) {
            JOptionPane.showMessageDialog(null, "Nomor HP Mahasiswa tidak boleh mengandung huruf.");
        }
        
        try {
            Mahasiswa.updateMahasiswa(nimmahasiswa, namamahasiswa, alamatmahasiswa, nohpmahasiswa, emailmahasiswa, prodi);
            model.setValueAt(namamahasiswa, row, 1);
            model.setValueAt(alamatmahasiswa, row, 2);
            model.setValueAt(nohpmahasiswa, row, 3);
            model.setValueAt(emailmahasiswa, row, 4);
            JOptionPane.showMessageDialog(null, "Data mahasiswa dengan NIM " + nimmahasiswa + " telah diubah.");
            selectRow();
        } catch (SQLException ex) {
            Logger.getLogger(crudMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Gagal mengubah data mahasiswa dengan NIM " + nimmahasiswa);
        }
    } 
}
  
    }//GEN-LAST:event_ubahActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new crudMahasiswa().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
        if(adaItemDipilih()) {
            selectRow();
        }else {
            // Tampilkan peringatan bahwa pengguna belum memilih item
            JOptionPane.showMessageDialog(this, "Anda belum memilih item. Silakan pilih item terlebih dahulu.");
            }
    }//GEN-LAST:event_tampilActionPerformed
    private boolean adaItemDipilih() {
        // Mengambil indeks baris yang dipilih dari JTable
        int selectedRow = tampil1.getSelectedRow();

        // Memeriksa apakah ada baris yang dipilih
        return selectedRow != -1; // Jika tidak ada baris yang dipilih, kembalikan false  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ubahmahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ubahmahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatmhs;
    private javax.swing.JTextField emailmhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField namamhs;
    private javax.swing.JTextField nimmhs;
    private javax.swing.JTextField nohpmhs;
    private javax.swing.JTextField programmhs;
    private javax.swing.JButton tampil;
    private javax.swing.JTable tampil1;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
